//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigPicPot.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PigPicPot.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 anime 的本地化字符串。
        /// </summary>
        public static string AnimeFilterButtonText {
            get {
                return ResourceManager.GetString("AnimeFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy as file 的本地化字符串。
        /// </summary>
        public static string ContextMenuCopyFile {
            get {
                return ResourceManager.GetString("ContextMenuCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to... 的本地化字符串。
        /// </summary>
        public static string ContextMenuExportTo {
            get {
                return ResourceManager.GetString("ContextMenuExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy as File 的本地化字符串。
        /// </summary>
        public static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy as Static Image 的本地化字符串。
        /// </summary>
        public static string CopyStatic {
            get {
                return ResourceManager.GetString("CopyStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dynamic 的本地化字符串。
        /// </summary>
        public static string DynamicFilterButtonText {
            get {
                return ResourceManager.GetString("DynamicFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to copy: 的本地化字符串。
        /// </summary>
        public static string ErrorFailedToCopy {
            get {
                return ResourceManager.GetString("ErrorFailedToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export: 的本地化字符串。
        /// </summary>
        public static string ErrorFailedToExport {
            get {
                return ResourceManager.GetString("ErrorFailedToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The image has been copied to the clipboard 的本地化字符串。
        /// </summary>
        public static string ImageCopiedNotification {
            get {
                return ResourceManager.GetString("ImageCopiedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading images... 的本地化字符串。
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied as file! 的本地化字符串。
        /// </summary>
        public static string NotificationCopiedFile {
            get {
                return ResourceManager.GetString("NotificationCopiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied as image! 的本地化字符串。
        /// </summary>
        public static string NotificationCopiedImage {
            get {
                return ResourceManager.GetString("NotificationCopiedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied as static image! 的本地化字符串。
        /// </summary>
        public static string NotificationCopiedStatic {
            get {
                return ResourceManager.GetString("NotificationCopiedStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exported to 的本地化字符串。
        /// </summary>
        public static string NotificationExportedTo {
            get {
                return ResourceManager.GetString("NotificationExportedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string OtherFilterButtonText {
            get {
                return ResourceManager.GetString("OtherFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 real 的本地化字符串。
        /// </summary>
        public static string RealFilterButtonText {
            get {
                return ResourceManager.GetString("RealFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Static 的本地化字符串。
        /// </summary>
        public static string StaticFilterButtonText {
            get {
                return ResourceManager.GetString("StaticFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zhuxx 的本地化字符串。
        /// </summary>
        public static string ZhuxxFilterButtonText {
            get {
                return ResourceManager.GetString("ZhuxxFilterButtonText", resourceCulture);
            }
        }
    }
}
