//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigPicPot.Strings {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PigPicPot.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        public static string CopyStatic {
            get {
                return ResourceManager.GetString("CopyStatic", resourceCulture);
            }
        }

        public static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }

        public static string NotificationCopiedImage {
            get {
                return ResourceManager.GetString("NotificationCopiedImage", resourceCulture);
            }
        }

        public static string NotificationCopiedStatic {
            get {
                return ResourceManager.GetString("NotificationCopiedStatic", resourceCulture);
            }
        }

        public static string NotificationCopiedFile {
            get {
                return ResourceManager.GetString("NotificationCopiedFile", resourceCulture);
            }
        }

        public static string ErrorFailedToCopy {
            get {
                return ResourceManager.GetString("ErrorFailedToCopy", resourceCulture);
            }
        }
    }
}
