//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PigPicPot.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PigPicPot.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to which favorite?.
        /// </summary>
        public static string AddToWhichFavorite {
            get {
                return ResourceManager.GetString("AddToWhichFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anime.
        /// </summary>
        public static string AnimeFilterButtonText {
            get {
                return ResourceManager.GetString("AnimeFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application update available!.
        /// </summary>
        public static string ApplicationUpdateAvailable {
            get {
                return ResourceManager.GetString("ApplicationUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default favorite cannot be deleted..
        /// </summary>
        public static string CannotDeleteDefault {
            get {
                return ResourceManager.GetString("CannotDeleteDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default favorite cannot be renamed..
        /// </summary>
        public static string CannotRenameDefault {
            get {
                return ResourceManager.GetString("CannotRenameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the favorite &apos;{0}&apos;?.
        /// </summary>
        public static string ConfirmDeleteFavorite {
            get {
                return ResourceManager.GetString("ConfirmDeleteFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as file.
        /// </summary>
        public static string ContextMenuCopyFile {
            get {
                return ResourceManager.GetString("ContextMenuCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to....
        /// </summary>
        public static string ContextMenuExportTo {
            get {
                return ResourceManager.GetString("ContextMenuExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as File.
        /// </summary>
        public static string CopyFile {
            get {
                return ResourceManager.GetString("CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as Static Image.
        /// </summary>
        public static string CopyStatic {
            get {
                return ResourceManager.GetString("CopyStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Favorite.
        /// </summary>
        public static string CreateFavorite {
            get {
                return ResourceManager.GetString("CreateFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic.
        /// </summary>
        public static string DynamicFilterButtonText {
            get {
                return ResourceManager.GetString("DynamicFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new favorite name:.
        /// </summary>
        public static string EnterNewFavoriteName {
            get {
                return ResourceManager.GetString("EnterNewFavoriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy:.
        /// </summary>
        public static string ErrorFailedToCopy {
            get {
                return ResourceManager.GetString("ErrorFailedToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export:.
        /// </summary>
        public static string ErrorFailedToExport {
            get {
                return ResourceManager.GetString("ErrorFailedToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite name cannot be empty or already exist..
        /// </summary>
        public static string FavoriteNameError {
            get {
                return ResourceManager.GetString("FavoriteNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image already in {0}.
        /// </summary>
        public static string ImageAlreadyInFavorite {
            get {
                return ResourceManager.GetString("ImageAlreadyInFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to {0}.
        /// </summary>
        public static string AddedToFavorite {
            get {
                return ResourceManager.GetString("AddedToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed from {0}.
        /// </summary>
        public static string RemovedFromFavorite {
            get {
                return ResourceManager.GetString("RemovedFromFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image has been copied to the clipboard.
        /// </summary>
        public static string ImageCopiedNotification {
            get {
                return ResourceManager.GetString("ImageCopiedNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading images....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied as file!.
        /// </summary>
        public static string NotificationCopiedFile {
            get {
                return ResourceManager.GetString("NotificationCopiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied as image!.
        /// </summary>
        public static string NotificationCopiedImage {
            get {
                return ResourceManager.GetString("NotificationCopiedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied as static image!.
        /// </summary>
        public static string NotificationCopiedStatic {
            get {
                return ResourceManager.GetString("NotificationCopiedStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported to.
        /// </summary>
        public static string NotificationExportedTo {
            get {
                return ResourceManager.GetString("NotificationExportedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherFilterButtonText {
            get {
                return ResourceManager.GetString("OtherFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to real.
        /// </summary>
        public static string RealFilterButtonText {
            get {
                return ResourceManager.GetString("RealFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Favorite.
        /// </summary>
        public static string RenameFavorite {
            get {
                return ResourceManager.GetString("RenameFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming favorite &apos;{0}&apos;. Enter new name:.
        /// </summary>
        public static string RenamingFavorite {
            get {
                return ResourceManager.GetString("RenamingFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite &apos;{0}&apos; renamed to &apos;{1}&apos;.
        /// </summary>
        public static string FavoriteRenamed {
            get {
                return ResourceManager.GetString("FavoriteRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite &apos;{0}&apos; deleted.
        /// </summary>
        public static string FavoriteDeleted {
            get {
                return ResourceManager.GetString("FavoriteDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource update available!.
        /// </summary>
        public static string ResourceUpdateAvailable {
            get {
                return ResourceManager.GetString("ResourceUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Favorite.
        /// </summary>
        public static string SelectFavorite {
            get {
                return ResourceManager.GetString("SelectFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string StaticFilterButtonText {
            get {
                return ResourceManager.GetString("StaticFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zhuxx.
        /// </summary>
        public static string ZhuxxFilterButtonText {
            get {
                return ResourceManager.GetString("ZhuxxFilterButtonText", resourceCulture);
            }
        }
    }
}
